name: Tests And Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - name: Check Swift version
      run: swift --version
    - name: Test and gather code coverage
      run: swift test --enable-code-coverage
    - name: Generate report
      run: |
        xcrun llvm-cov show \
          .build/debug/CombineValidatePackageTests.xctest/Contents/MacOS/CombineValidatePackageTests \
          -instr-profile=".build/debug/codecov/default.profdata" \
          -ignore-filename-regex=".build|Tests" > coverage.txt
    - name: Upload report
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      run: |
        bash <(curl -s https://codecov.io/bash)
